# Generated by Django 3.2.5 on 2021-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygensuppliers',
            name='district',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='oxygensuppliers',
            name='name_of_supplier',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='oxygensuppliers',
            name='groupname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
