# Generated by Django 3.2.5 on 2021-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20210730_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygensuppliers',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
